eth-sri/lmql

src/lmql/model/serve.py
Currently the model starts up and runs the server while the model and tokenizer are loading. 
The client cannot tell when the model & tokenizer are ready, so they could send requests during this period. However, since models often take a long time to load, if the client sends a request during this period, they get a timeout, and an exception is raised. 
A simple solution to this is to add an optional flag that tells the model server not to run until after the model and tokenizer are loaded. That way the client can know not to send requests while the model is loading (since the port is not open)
In some use cases where a python script wants to host a model and query inference, having this optional flag would be really convenient.
Since this is an optional flag, it doesn't change the …
=> Added the option to wait for model & tokenizer in lmql.model.serve

README.md, docs/source/installation.md, docs/source/language/models.md, docs/source/language/overview.md, docs/source/language/scripted_prompts.md
Amazing library 👏🤩
This MR fixes some typos I've found reading the docs and going through the examples.
The word "travelling" (with two 'll') appears several times, I think it's also a typo, right? If so, I can open a second small MR to fix this too.
I also don't know what "saskaers" means in `docs/source/language/scripted_prompts.md`
Thanks!
=> Fix typos in docs

src/lmql/model/serve.py
Hello!
I use a relatively mid-range graphics card for my work, which with LMQL loading models at full precision meant I got better performance from CPU inference than I do from GPU inference. Half precision also doesn't work with the model I'd like to use.
This PR should provide 8bit support for those who opt in with `--dtype 8bit` under `serve_model`. I also took the liberty of adding a help string to that option. The `8bit` dtype only applies when loading with `--cuda`, otherwise it's entirely ignored (not passed to HuggingFace at all.)
Hope this helps others, too!
=> Add 8-bit support on CUDA via HuggingFace's load_in_8bit

src/lmql/runtime/bopenai/openai_api.py
This PR adds support for Azure OpenAI, it allows for configuring multiple deployments as environment variables (an difficult aspect to consolidate with LMQL)
This solution breaks the least amount for support for LMQL if it is used by libraries building upon LMQL and examples, all a user needs to do is to deploy models in whatever azure openai service they have and add the environment variables to support them.
To use Azure OpenAI instead of regular OpenAI, you need to have an environment variable, OPENAI_API_TYPE, set to "azure"
In order to store the deployments we convert model names into parts of environment variables, so a deployment for gpt-3.5-turbo needs these environment variables:
AZURE_OPENAI_GPT-3_5-TURBO_ENDPOINT
AZURE_OPENAI_GPT-3_5-TURBO_KEY
This might look messy, but this is …
=> Add support for Azure OpenAI deployments

src/lmql/models/lmtp/utils.py
This fixes the issue noted in #94 , as well as other `--dtype` arguments that may not have been parsed correctly.
- Ignore dtype model arg if `8bit` specified as `--dtype` argument (only set `load_in_8bit` instead)
- Use `getattr` to parse string value (turning `"float16"` into `torch.float16` etc.)
=> Fix dtype parsing

docs/source/language/llama.cpp.md, docs/source/language/models.md, src/lmql/models/lmtp/backends/__init__.py, src/lmql/models/lmtp/backends/__main__.py, src/lmql/models/lmtp/backends/llama_cpp_model.py, src/lmql/models/lmtp/backends/lmtp_model.py, src/lmql/models/lmtp/backends/transformers_model.py, src/lmql/models/lmtp/lmtp_async.py, src/lmql/models/lmtp/lmtp_dcmodel.py, src/lmql/models/lmtp/lmtp_inference_server.py, src/lmql/models/lmtp/lmtp_scheduler.py, src/lmql/models/lmtp/lmtp_serve.py, src/lmql/models/model.py, src/lmql/runtime/dclib/decoders.py, src/lmql/runtime/interpreter.py, src/lmql/runtime/model_registry.py, src/lmql/ui/playground/src/App.jsx
This PR adds a llama.cpp LMTP backend for use in LMQL. It also adds a chapter to the documentation on how to use llama.cpp models.
=> llama.cpp backend

src/lmql/models/lmtp/lmtp_scheduler.py
Solves #125 
I did a tiny bit of math to get exactly how long of the 0.1 seconds remained after each wake-up, then setting the timeout for that long. This keeps nearly identical behavior (perhaps slightly lower throughput under absolute max load) but eliminates virtually all idle CPU usage.
Before:
After:
=> Change LMTP scheduler polling to get with timeout

src/lmql/models/lmtp/backends/transformers_model.py, src/lmql/models/lmtp/lmtp_serve.py
This PR addresses the need to use GPTQ-quantized models, which can't currently be loaded with the transformers library.
It introduces an optional `--loader` flag with support for the `auto-gptq` option. When this option is specified, the (quantized) model will be loaded using the `auto_gptq` library.
To serve the model, run the following command:
```
lmql serve-model TheBloke/WizardCoder-15B-1.0-GPTQ --cuda --loader auto-gptq --use_safetensors true
```
or use the in-process invocation with:
```
from lmql.model("local:TheBloke/WizardCoder-15B-1.0-GPTQ", cuda=True, loader="auto-gptq", use_safetensors=True)
```
=> Add support for GPTQ quantization

src/lmql/models/lmtp/lmtp_scheduler.py
Corrects mistake noted in a comment in #127 and also allows checking for the full 0.1 seconds even when the queue comes back as empty.
Related to (and solves) #125
=> Fix lmtp_scheduler batching to take no more than 0.1 seconds

setup.cfg
Without this, `python setup.py develop` could fail when trying to build an aiohttp release incompatible with Python 3.10 (see https://github.com/aio-libs/aiohttp/issues/6898 re the underlying issue).
=> Avoid abandoned/broken 4.0 release branch of aiohttp

src/lmql/ui/playground/src/remote_process.js
When started with `lmql playground`, `REACT_APP_SOCKET_PORT` is always set so this should be a noop.
(Refactoring out changes that aren't Nix-specific from #139).
=> playground: default to port used to load current page, not 3004

src/lmql/ui/live/live.js
Might be room for further culling as well (do we really need `content_dir` at all?); acting conservatively.
=> live.js: prune code serving from a "base" directory that no longer exists

src/lmql/models/model.py, src/lmql/runtime/model_registry.py
When running LMQL with llama.cpp and OpenLlama 7B, the wrong tokenizer (huggyllama/llama-7b) gets loaded. Specifying a tokenizer by using `lmql.model("llama.cpp:...", tokenizer="danielhanchen/open_llama_3b")` doesn't solve that problem, because the tokenizer is hardcoded for llama.cpp models.
This PR allows specifying a tokenizer for llama.cpp models, fixing https://github.com/eth-sri/lmql/issues/154.
=> Fix hardcoded tokenizer for llama.cpp models

src/lmql/ui/live/live.js, src/lmql/ui/live/package.json, src/lmql/ui/live/yarn.lock
Nix sets all mtimes to one second past epoch to make builds more reproducible. Consequently, `Last-Modified` times are not useful under `/nix/store`; however, because store paths include a hash (and thus are different between builds of non-identical source trees), _a hash of any given store path_ itself suffices as a unique identifier.
=> live.js: When serving content from /nix/store, configure cache headers appropriately

src/lmql/__init__.py
It's a simple fix, as at the moment the `run_file` function does not respect `output_writer` kwarg.
I've grep'd the code and didn't any code in lmql that would break, but as far as API is concerned this is a "breaking" (?) change because the default output writer used downstream is "silent".
=> Respect "output_writer" parameter of run_file func

src/lmql/runtime/bopenai/__init__.py
Fixes issue when running in async streamlit, where after completing an @query decorated function, async workers would close.
Without this setting, the following error is triggered:
```python
if not self.is_available():
raise APIShutDownException(f"bopenai requires at least one worker to be running to issue new complete requests.")
```  
Note that relaunching the API means that logging & cost-tracking are not always persisted.
=> bugfix: relaunch OpenAI API if workers close

README.md, docs/source/installation.md, docs/source/language/openai.md, src/lmql/runtime/bopenai/openai_api.py, src/lmql/runtime/openai_secret.py
I did a minor code refactoring for `openai_secret.py` module and updated related docs that i was able to find
**Motivation**
I've been looking for a way to set `openai_org` from env variable and did not find it in docs. Looking at the code, i found that this is already implemented by looking at `LMQL_OPENAI_ORG` parameter. While updating the docs, i've made some improvements (?) to the code that should make it easier to operate.
**Changes**
* Minor refactoring of the file (split a function into separate block for easier reading)
* `LMQL_OPENAI_ORG` can now be used with `OPENAI_API_KEY` (was previously only used with `LMQL_OPENAI_SECRET`)
* `LMQL_OPENAI_SECRET` can now be used without setting `LMQL_OPENAI_ORG`
* Removed a clause that was never working(?) (see comments)
* Error message now …
=> Refactor openai secret loading

src/lmql/models/lmtp/utils.py
I found the current input options specified for the invoking of local models to be very unsatisfactory. The specification of quantisation being exclusive with dtype specification is wrong since they are separate arguments and removes the ability to specify brain-float and 4bit quantisation which is the optimum strategy by the original qlora developers. In addition, simply adding 4bit quantisation is not enough, specifying a BitsAndBytesConfig object is necessary for double_quantisation features and more.
Current method is rather hacky with the passing of quantization parameters as a frozenset to get around objects/dictionaries not being hashable. Alternative approaches for the same outcome are welcome.
=> adjustments to model naming arguments for adding quantization config

docs/_components/LMHero.vue
/guide/ does not exist, it appears this has been relocated to top level /docs/.
=> Fix broken "Get Started" link

CONTRIBUTING.md, README.md, docs/.vitepress/link-checker.js, docs/blog/posts/release-0.0.6.4.md, scripts/flake.d/pyproject.toml, setup.cfg, src/lmql/models/lmtp/README.md, src/lmql/runtime/openai_secret.py, src/lmql/ui/playground/src/App.jsx, src/lmql/ui/playground/src/Explore.jsx, src/lmql/ui/vscode/README.md
replaces 'docs.lmql.ai' with 'lmql.ai/docs', updates all broken links to their current versions
=> Fixes doc urls

src/lmql/runtime/tracing/tracer.py
I'm not sure what the purpose of this function is, but it seems like it was not called properly.
Fixes the following error on Colab:
```python
import lmql
model = lmql.model("openai/gpt-3.5-turbo-instruct")
await model.score("Hello", ["World", "Apples", "Oranges"])
```
Feel free to close if not correct / doesn't actually fix anything. I did notice that the tracer seemed to be initialized here https://github.com/eth-sri/lmql/blob/ab02526ddf9883aff4acda4e76c5a2a1cc136bf1/src/lmql/runtime/tracing/tracer.py#L156 so I'm not 100% sure what `_ensure_tracer()` is supposed to do.
=> Fixed bug where ContextTracer wasn't properly initializing a tracer

MANIFEST.in
Fixes an unresolved merge conflict in MANIFEST.in and removes trailing slashes so local building also works on Windows
Should likely be tested on Linux, but works on WSL
=> Fix MANIFEST.in for proper build
